INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE ) 
    VALUES ( 0, "Mongolia", "モングル", "Ulan-Bator", "ウランーバトル", 47.88, 106.91 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 1, "Japan", "日本", "Fukuoka", "福岡", 33.60, 130.39 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 2, "Japan", "日本", "Ibaraki", "茨城", 36.06, 140.14 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 3, "Japan", "日本", "Osaka", "大阪", 34.69, 135.50 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 4, "Japan", "日本", "Aichi", "愛知", 35.18, 136.91 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 5, "Japan", "日本", "Akita", "秋田", 39.72, 140.10 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 6, "Japan", "日本", "Aomori", "青森", 40.82, 140.75 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 7, "Brazil", "ブラジル", "Sao Paulo", "サンパウロ", -23.57, -46.61 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 8, "Bulgaria", "ブルガリア", "Sofia", "ソフィア", 42.70, 23.32 );    
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 9, "Canada", "カナダ", "British Columbia", "ブリティッシュコロンビア", 55.0, -127.40 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 10, "Japan", "日本", "Chiba", "千葉", 35.61, 140.11 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 11, "China", "中国", "Liaoning", "遼寧", 41.65, 123.25 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 12, "China", "中国", "Inner Mongolia", "内モンゴル自治", 43.98, 115.43 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 13, "Egypt", "エジプト", "Dhakaria", "ダカリーヤ", 30.13, 31.27 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 14, "Japan", "日本", "Ehime", "愛媛", 33.73, 132.79 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 15, "Japan", "日本", "Ehime", "福井", 36.06, 136.22 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 16, "Japan", "日本", "Fukushima", "福島", 37.76, 140.47 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 17, "Georgia", "グルジア", "Tbilissi", "トビリシ", 41.72, 44.80 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 18, "Georgia", "グルジア", "Mtskheta", "ムツケタ", 41.84, 44.71 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 19, "Japan", "日本", "Gifu", "岐阜", 35.44, 136.76 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 20, "Japan", "日本", "Gunma", "群馬", 36.54, 139.02 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 21, "Japan", "日本", "Hiroshima", "広島", 34.39, 132.46 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 22, "Japan", "日本", "Hokkaido", "北海道", 43.11, 141.59 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 23, "Hungary", "ハンガリー", "Jasz-Nagykun-Szolnok", "ヤース・ナジタン・ソルノク", 47.21, 20.29 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 24, "Japan", "日本", "Hyogo", "兵庫", 34.76, 135.07 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 25, "Japan", "日本", "Ishikawa", "石川", 36.54, 136.62 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 26, "Japan", "日本", "Iwate", "岩手", 39.73, 141.13 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 27, "Japan", "日本", "Kagawa", "香川", 34.28, 133.83 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 28, "Japan", "日本", "Kagoshima", "鹿児島", 31.60, 130.56 );    
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 29, "Japan", "日本", "Kanagawa", "神奈川", 35.45, 139.62 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 30, "Japan", "日本", "Kochi", "高知", 33.56, 133.53 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 31, "Japan", "日本", "Kochi", "高知", 33.56, 133.53 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 32, "Korea", "韓国", "Seoul", "ソウル", 37.55, 127.00 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 33, "Japan", "日本", "Kumomoto", "熊本", 32.82, 130.71 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 34, "Japan", "日本", "Kyoto", "京都", 35.01, 135.77 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 35, "Japan", "日本", "Mie", "三重", 34.44, 136.79 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 36, "Japan", "日本", "Miyagi", "宮城", 38.27, 140.86 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 37, "Japan", "日本", "Miyazaki", "宮崎", 31.91, 131.42 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 38, "Japan", "日本", "Nagano", "長野", 36.67, 138.20 );    
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE ) 
    VALUES ( 39, "Mongolia", "モングル", "Arkhangai", "アルハンガイ", 47.56, 101.28 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE ) 
    VALUES ( 40, "Mongolia", "モングル", "Altanbulag", "アルタンボラグ", 47.72, 106.37 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 41, "Japan", "日本", "Nagasaki", "長崎", 32.79, 129.87 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 42, "Japan", "日本", "Nara", "奈良", 34.67, 135.81 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 43, "Japan", "日本", "Niigata", "新潟", 37.91, 139.04 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 44, "Japan", "日本", "Oita", "大分", 33.22, 131.61 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 45, "Japan", "日本", "Okayama", "岡山", 34.66, 133.92 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 46, "Japan", "日本", "Okinawa", "沖縄", 26.36, 127.81 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 47, "Japan", "日本", "Saga", "佐賀", 33.27, 130.29 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 48, "Japan", "日本", "Saitama", "埼玉", 35.86, 139.64 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 49, "Japan", "日本", "Shiga", "滋賀", 35.06, 136.00 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 50, "Japan", "日本", "Shimane", "島根", 35.35, 132.74 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 51, "Japan", "日本", "Shizuoka", "静岡", 34.97, 138.38 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 52, "Japan", "日本", "Tochigi", "栃木", 36.52, 139.86 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 53, "Japan", "日本", "Tokushima", "徳島", 34.07, 134.56 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 54, "Japan", "日本", "Tokyo", "都京", 35.71, 139.73 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 55, "Japan", "日本", "Tottori", "鳥取", 35.51, 134.23 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 56, "Japan", "日本", "Toyama", "富山", 36.70, 137.21 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 57, "Japan", "日本", "Wakayama", "和歌山", 34.24, 135.18 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 58, "Japan", "日本", "Yamagata", "山形", 38.27, 140.34 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 59, "Japan", "日本", "Yamanashi", "山梨", 35.49, 138.81 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 60, "Russia", "ロシア", "Lesozavodsk", "レソザボズク", 45.47, 133.40 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 61, "Russia", "ロシア", "Buryat Republic", "ブリヤート共和", 45.47, 133.40 );
INSERT INTO APP.LOCATIONS( ID, EN_COUNTRY, JP_COUNTRY, EN_AREA, JP_AREA, LONGITUDE, LATITUDE )  
    VALUES ( 62, "USA", "米国", "Hawaii", "ハワイ", 21.35, -157.73 );    