package com.nate.sumo.model.basho;

import com.nate.sumo.model.common.Name;

public enum Kimarite {

	ABISETAOSHI( new Name( "Abisetaoshi", "浴せ倒し")),
	OSHIDASHI( new Name( "Oshidashi", "押し出し")),
	YORIKIRI( new Name( "Yorikiri", "寄り切り")),
	OSHITAOSHI( new Name( "Oshitaoshi", "押し倒し")),
	YORITAOSHI( new Name( "Yoritaoshi", "寄り倒し")),
	UWATENAGE( new Name( "Uwatenage", "上手投げ")),
	SHITATENAGE( new Name( "Shitatenage", "下手投げ")),
	SUKUINAGE( new Name( "Sukuinage", "掬い投げ")),
	HATAKIKOMI( new Name( "Hatakikomi", "叩き込み")),
	HANSOKU( new Name( "Hansoku", "反則")),
	FUSENSHO( new Name( "Fusensho", "")),
	FUSEN( new Name( "Fusen", "")),
	SOTOGAKE( new Name( "Sotogake", "外掛け")),
	UCHIGAKE( new Name( "Uchigake", "内掛け")),
	TSUKIOTOSHI( new Name( "Tsukiotoshi", "突き落とし")),
	TSUKITAOSHI( new Name( "Tsukitaoshi", "突き倒し")),
	OKURIDASHI( new Name( "Okuridashi", "送り出し")),
	UWATEDASHINAGE( new Name( "Uwatedashinage", "上手出し投げ")),
	SHITATEDASHINAGE( new Name( "Shitatedashinage", "下手出し投げ")),
	KUBINAGE( new Name( "Kubinage", "首投げ")),
	UTCHARI( new Name( "Utchari", "うっちゃり")),
	WATASHIKOMI( new Name( "Watashikomi", "渡し込み" ) ),
	TSUKIDASHI( new Name( "Tsukidashi", "突き出し")),
	IPPONZEOI( new Name( "Ipponzeoi", "本背負い")),
	KAKENAGE( new Name( "Kakenage", "掛け投げ")),
	KOSHINAGE( new Name( "Koshinage", "腰投げ")),
	KOTENAGE( new Name( "Kotenage", "小手投げ")),
	NICHONAGE( new Name( "Nichonage", "二丁投げ")),
	TSUKAMINAGE( new Name( "Tsukaminage", "つかみ投げ")),
	YAGURANAGE( new Name( "Yaguranage", "櫓投げ")),
	ASHITORI( new Name ("Ashitori", "足取り")),
	CHONGAKE( new Name( "Chongake", "ちょん掛け")),
	KAWAZUNAGE( new Name( "Kawazunage", "河津掛け")),
	KEKAESHI( new Name( "Kekaeshi", "蹴返し")),
	KETAGURI( new Name( "Ketaguri", "蹴手繰り")),
	KIRIKAESHI( new Name( "Kirikaeshi", "切り返し")),
	KOMATASUKUI( new Name( "Komatasukui", "小股掬い")),
	KOZUMATORI( new Name( "Kozumatori", "小褄取り")),
	MITOKOROZEME( new Name( "Mitokorozeme", "三所攻め")),
	NIMAIGERI( new Name( "Nimaigeri", "二枚蹴り")),
	OMATA( new Name( "Omata", "大股")),
	SOTOKOMATA( new Name( "Sotokomata", "外小股")),
	SUSOHARAI( new Name( "Susoharai", "裾払い")),
	SUSOTORI( new Name( "Susotori", "裾取り")),
	TSUMATORI( new Name( "Tsumatori", "褄取り")),
	AMIUCHI( new Name( "Amiuchi", "網打ち")),
	GASSHOHINERI( new Name( "Gasshohineri", "合掌捻り")),
	HARIMANAGE( new Name( "Harimanage", "波離間投げ")),
	KAINAHINERI( new Name( "Kainahineri", "腕捻り")),
	KATASUKASHI( new Name( "Katasukashi", "肩透かし")),
	KOTEHINERI( new Name( "Kotohineri", "小手捻り")),
	KUBIHINERI( new Name( "Kubihineri", "首捻り")),
	MAKIOTOSHI( new Name( "Makiotoshi", "巻き落とし")),
	OSAKATE( new Name( "Osakate", "大逆手")),
	SABAORI( new Name( "Sabaori", "鯖折り")),
	SAKATOTTARI( new Name( "Sakatottari", "鯖折り")),
	SHITATEHINERI( new Name( "Shitatehineri", "下手捻り")),
	SOTOMUSO( new Name( "Sotomuso", "外無双")),
	TOKKURINAGE( new Name( "Tokkurinage", "徳利投げ")),
	TOTTARI( new Name( "Tottari", "とったり")),
	UCHIMUSO( new Name( "Uchimuso", "内無双")),
	UWATEHINERI( new Name( "Uwatehineri", "上手捻り")),
	ZUBUNERI( new Name( "Zubuneri", "ずぶねり")),
	IZORI( new Name( "Izori", "居反り")),
	KAKEZORI( new Name( "Kakezori", "掛け反り")),
	SHUMOKUZORI( new Name( "Shumokuzori", "撞木反り")),
	SOTOTASUKIZORI( new Name( "Sototasukizori", "外たすき反り")),
	TASUKIZORI( new Name( "Tasukizori", "たすき反り")),
	TSUTAEZORI( new Name( "Tsutaezori", "伝え反り")),
	HIKIOTOSHI( new Name( "Hikiotoshi", "引き落とし")),
	HIKKAKE( new Name( "Hikkake", "引っ掛け")),
	KIMEDASHI( new Name( "Kimedashi", "極め出し")),
	KIMETAOSHI( new Name( "Kimetaoshi", "極め倒し")),
	OKURIGAKE( new Name( "Okurigake", "送り掛け")),
	OKURIHIKIOTOSHI( new Name( "Okurihikiotoshi", "送り引き落とし")),
	OKURINAGE( new Name( "Okurinage", "送り投げ")),
	OKURITAOSHI( new Name( "Okuritaoshi", "送り倒し")),
	OKURITSURIDASHI( new Name( "Okuritsuridashi", "送り吊り出し")),
	OKURITSURIOTOSHI( new Name( "Okuritsuriotoshi", "送り吊り落とし")),
	SOKUBIOTOSHI( new Name( "Sokubiotoshi", "素首落とし")),
	TSURIDASHI( new Name( "Tsuridashi", "吊り出し")),
	TSURIOTOSHI( new Name( "Tsuriotoshi", "吊り落とし")),
	USHIROMOTARE( new Name( "Ushiromotare", "後ろもたれ")),
	WARIDASHI( new Name( "Waridashi", "割り出し")),
	YOBIMODOSHI( new Name( "Yobimodoshi", "呼び戻し")),
	FUMIDASHI( new Name( "Fumidashi", "踏み出し")),
	ISAMIASHI( new Name( "Isamiashi", "勇み足")),
	KOSHIKUDAKE( new Name( "Koshikudake", "腰砕け")),
	TSUKIHIZA( new Name( "Tsukihiza", "つきひざ")),
	TSUKITE( new Name( "Tsukite", "つき手"));
	
	private Name name;
	
	private Kimarite( Name aName ){
		this.name = aName;
	}
	
	public Name getName(){
		return name;
	}
}
